import type { CommunityTopic, CommunityBroadcast, CommunityEvent } from './community-types'

export const mockTopics: CommunityTopic[] = [
  {
    id: 'topic-1',
    icon: '👵',
    title: '高齡犬貓照護',
    description: '伴隨愛寵優雅老去，專屬老毛孩的日常保養、關節照護與溫馨經驗分享。',
    members: '3.2K',
    isMock: true,
  },
  {
    id: 'topic-2',
    icon: '💧',
    title: '腎臟病交流',
    description: '腎衰竭毛孩飲食調配、皮下輸液技巧、處方飼料與定期檢驗數據追蹤討論。',
    members: '2.5K',
    moderator: '專業獸醫林醫師',
    isMock: true,
  },
  {
    id: 'topic-3',
    icon: '🧠',
    title: '癲癇與神經科',
    description: '提供癲癇毛孩照護日記交流、藥物控制心得、發作時的安全防護避難措施。',
    members: '1.1K',
    isMock: true,
  },
  {
    id: 'topic-4',
    icon: '🍃',
    title: '皮膚敏感過敏',
    description: '異位性皮膚炎、濕疹、過敏原檢測經驗、抗敏飲食與洗劑保養推薦。',
    members: '4.8K',
    isMock: true,
  },
  {
    id: 'topic-5',
    icon: '❤️',
    title: '心臟病關懷',
    description: '心臟肥大、二尖瓣退化毛孩的居家安靜照護、服藥記錄、喘息監測與心臟超音波分享。',
    members: '1.9K',
    isMock: true,
  },
  {
    id: 'topic-6',
    icon: '🥩',
    title: '飲食與營養',
    description: '鮮食生食調配、主食罐挑選、高體重控管、各年齡階段毛孩所需營養素解析。',
    members: '5.4K',
    moderator: '營養師小陳',
    isMock: true,
  },
  {
    id: 'topic-7',
    icon: '🍼',
    title: '幼犬幼貓成長',
    description: '新手家長必看！疫苗時程、社會化訓練、離乳期餵食、基礎定點大小便教導。',
    members: '6.1K',
    isMock: true,
  },
]

export const mockBroadcasts: CommunityBroadcast[] = [
  {
    id: 'bc-1',
    hospital: '台北愛毛獸醫醫院',
    announcement: '配合端午連假，6/14 ~ 6/16 門診時間調整為僅提供上午急診服務，下午及夜間休診，請毛家長多加留意。',
    date: '2026-06-10',
    priority: 'normal',
    verified: true,
    notificationEnabled: true,
    isMock: true,
  },
  {
    id: 'bc-2',
    hospital: '全心動物心臟專科',
    announcement: '【緊急通知】本院即時引進最新型心臟微創導管手術設備，若有急性心衰衰竭病患，請立即撥打緊急救援專線。',
    date: '2026-07-29',
    priority: 'emergency',
    verified: true,
    notificationEnabled: true,
    isMock: true,
  },
  {
    id: 'bc-3',
    hospital: '萌寵皮膚康復中心',
    announcement: '季節性換季潮到來，預約過敏原檢測及洗劑治療目前門診量較大，建議提早一週線上排隊預約預防針。',
    date: '2026-07-28',
    priority: 'normal',
    verified: false,
    notificationEnabled: false,
    isMock: true,
  },
]

export const mockEvents: CommunityEvent[] = [
  {
    id: 'evt-1',
    type: 'seminar',
    title: '腎臟病毛孩的每日水分與飲食調配指引',
    date: '2026-08-05 19:30',
    aiSummary: '本講座將由獸醫權威深度解析如何安全計算每日飲水量，並現場示範如何調配高嗜口性低磷鮮食。',
    isMock: true,
  },
  {
    id: 'evt-2',
    type: 'live',
    title: '【直播】高齡犬貓關節保養與居家無障礙改建',
    date: '2026-08-12 20:00',
    aiSummary: '現場線上解答老犬老貓關節炎藥物使用時機，並提供居家防滑、斜坡板鋪設的實用改造法。',
    isMock: true,
  },
  {
    id: 'evt-3',
    type: 'activity',
    title: '萌寵夏日草地奔跑同樂會 (線下聚會)',
    date: '2026-08-23 14:00',
    isMock: true,
  },
  {
    id: 'evt-4',
    type: 'lecture',
    title: '犬貓急救黃金三分鐘：CPR與噎到哈姆立克法實作',
    date: '2026-09-02 15:00',
    aiSummary: '手把手演練心肺復甦術與急救呼吸技巧，為緊急意外發生時建立最堅強的生命防護線。',
    isMock: true,
  },
]
