import type { LocaleType } from '../i18n/translations'

export const publicSiteContent = {
  'zh-TW': {
    skip:'跳到主要內容', brand:'毛孩生活中心', nav:['理念','功能','旅程','安裝','常見問題'], app:'開啟 App', language:'English', eyebrow:'PET LIFE CENTER · PUBLIC BETA', title:'把每一天的照護，串成牠一生的故事。', lead:'毛孩生活中心是一個單機優先的照護夥伴，將提醒、觀察、健康時間軸、回憶與備份整理在同一個溫暖空間。', primary:'開始使用 PWA', secondary:'了解隱私設計', trust:'不需帳號 · 資料預設留在裝置 · 支援離線', missionTitle:'不是替你下判斷，而是陪你看見變化。', mission:'Guardian OS 將日常照護轉成清楚、可回顧的脈絡；它不提供診斷或治療建議，重要健康決策仍應由合格獸醫師判斷。', todayTitle:'Guardian Today', today:'依目前毛孩整理今日提醒、最近紀錄與值得留意的生活脈絡，幫助飼主專注下一件要做的事。', featuresTitle:'從今天，到牠完整的生活故事', journeyTitle:'Case Journey', journey:'把同一照護主題相關的觀察、提醒、回憶與附件整理成連續旅程，保留事件來源與時間順序。', installTitle:'安裝在你的手機上', install:'使用 Safari 或 Chrome 開啟網站，再選擇「加入主畫面／安裝應用程式」。核心資料與內建音樂可在支援的裝置上離線使用。', installCta:'立即開啟 App', faqTitle:'常見問題', faq:[['資料會上傳嗎？','目前核心照護資料採本機儲存，不會自動上傳。請定期匯出完整備份。'],['可以取代獸醫嗎？','不可以。本產品協助記錄與整理，不提供診斷、處方或緊急醫療判斷。'],['支援哪些語言？','公開測試基礎支援繁體中文與英文，可在設定中切換。'],['換手機怎麼辦？','請先下載完整備份檔，再於新裝置使用恢復功能。']], privacyTitle:'隱私優先', privacy:'照片、影片、錄音與照護紀錄預設保存在你的裝置。分享獸醫摘要前，請自行確認內容與接收對象。', termsTitle:'服務條款', terms:'本服務為生活紀錄工具。使用者需自行維護裝置安全與備份，並對匯入素材具合法使用權。', contactTitle:'與我們聯絡', contact:'產品建議、無障礙問題或公開測試回報', footer:'© 2026 毛孩生活中心 Pet Life Center', featureCards:[['照護提醒','安排餵食、用藥、回診、疫苗與日常照護。'],['故事時間軸','整合提醒、觀察、回憶與附件，保留時間脈絡。'],['生活觀察','從既有紀錄整理趨勢，不產生醫療診斷。'],['照片與影片','將珍貴片段附加在毛孩自己的生活故事中。'],['安全備份','匯出完整本機資料；另可產生不含媒體的獸醫摘要。'],['多毛孩空間','每一隻毛孩的提醒、紀錄與旅程分開呈現。']]
  },
  'en-US': {
    skip:'Skip to main content', brand:'Pet Life Center', nav:['Philosophy','Features','Journey','Install','FAQ'], app:'Open App', language:'繁體中文', eyebrow:'PET LIFE CENTER · PUBLIC BETA', title:'Turn everyday care into the story of a lifetime.', lead:'Pet Life Center is a local-first companion that brings reminders, observations, health timelines, memories, and backups into one calm place.', primary:'Start with the PWA', secondary:'Explore privacy', trust:'No account required · Local by default · Offline-ready', missionTitle:'We help you notice change — we never make the diagnosis.', mission:'Guardian OS organizes everyday care into a clear, reviewable context. It does not diagnose or recommend treatment; qualified veterinarians remain responsible for medical decisions.', todayTitle:'Guardian Today', today:'A focused view of today’s reminders, recent records, and relevant care context for the currently selected pet.', featuresTitle:'From today to a complete life story', journeyTitle:'Case Journey', journey:'Related observations, reminders, memories, and attachments are grouped into a continuous journey while preserving source and chronology.', installTitle:'Keep it on your phone', install:'Open the site in Safari or Chrome, then choose Add to Home Screen or Install App. Core local data and bundled music remain available offline on supported devices.', installCta:'Open the App', faqTitle:'Frequently asked questions', faq:[['Is my data uploaded?','Core care data is currently stored locally and is not uploaded automatically. Export regular backups.'],['Does this replace a veterinarian?','No. It supports recording and organization, not diagnosis, prescriptions, or emergency triage.'],['Which languages are supported?','The public beta foundation supports Traditional Chinese and English, selectable in Settings.'],['How do I move to a new phone?','Download a full backup first, then use Restore on the new device.']], privacyTitle:'Privacy first', privacy:'Photos, videos, recordings, and care records stay on your device by default. Verify the content and recipient before sharing a veterinary summary.', termsTitle:'Terms of service', terms:'This is a personal life-record tool. You are responsible for device security, backups, and the lawful use of imported material.', contactTitle:'Contact us', contact:'Product feedback, accessibility questions, and public beta reports', footer:'© 2026 Pet Life Center', featureCards:[['Care reminders','Plan feeding, medication, visits, vaccines, and everyday care.'],['Story timeline','Bring reminders, observations, memories, and attachments into chronological context.'],['Daily observations','Organize trends from existing records without generating medical diagnoses.'],['Photos and video','Attach meaningful moments to each pet’s own life story.'],['Safe backup','Export complete local data or a media-free veterinary summary.'],['Multi-pet spaces','Keep each pet’s reminders, records, and journeys clearly separated.']]
  }
} satisfies Record<LocaleType, Record<string, unknown>>
