import type { CareReminder, GrowthRecord, Pet, ReminderKind, RepeatRule } from './domain'
import { buildHealthTimeline } from './domain'
import { formatDate, formatTime, formatWeight } from './i18n/formatters'
import { getLocale, interpolate, translate, type LocaleType } from './i18n/translations'
import type { TranslationKeys } from './i18n/zh-TW'

type VetReportInput = { pet: Pet; reminders: CareReminder[]; growthRecords: GrowthRecord[]; generatedAt?: Date; locale?: LocaleType }
const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character] || character))
const kindKeys: Record<ReminderKind, TranslationKeys> = { medication: 'kindMedication', feeding: 'kindFeeding', vet: 'kindVet', vaccine: 'kindVaccine', care: 'kindCare' }
const repeatKeys: Record<RepeatRule, TranslationKeys> = { once: 'repeatOnce', daily: 'repeatDaily', weekly: 'repeatWeekly', monthly: 'repeatMonthly', quarterly: 'repeatQuarterly', yearly: 'repeatYearly' }
const statusKeys = { completed: 'reminderStatusCompleted', late: 'activityCompleted', skipped: 'activitySkipped', scheduled: 'statusTodo', recorded: 'recorded' } as const satisfies Record<string, TranslationKeys>

const reportStyles = `:root{font-family:"Noto Sans TC","PingFang TC","Microsoft JhengHei",Arial,sans-serif;color:#263b37;background:#eef3f1}*{box-sizing:border-box}body{margin:0}.toolbar{position:sticky;top:0;display:flex;justify-content:space-between;align-items:center;gap:16px;padding:12px 18px;background:#173f3b;color:#fff}.toolbar p{margin:0;font-size:14px}.toolbar button{border:0;border-radius:10px;padding:10px 16px;background:#fff;color:#173f3b;font-weight:800}main{width:min(100%,210mm);min-height:297mm;margin:18px auto;padding:16mm;background:#fff;box-shadow:0 12px 35px rgba(24,59,54,.12)}header{border-bottom:3px solid #6f91a7;padding-bottom:14px}h1{margin:0;font-size:28px;color:#173f3b}header p{margin:6px 0 0;color:#5e746f;font-size:13px}.notice{margin:16px 0;padding:11px 13px;border-left:4px solid #d3a665;background:#fff8ec;font-size:12px;line-height:1.65}section{break-inside:avoid;margin-top:20px}h2{margin:0 0 9px;font-size:18px;color:#284e48}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.fact{border:1px solid #dce7e4;border-radius:10px;padding:10px}.fact b,.fact span{display:block}.fact b{font-size:11px;color:#6d817c}.fact span{margin-top:3px;font-size:14px}table{width:100%;border-collapse:collapse;font-size:12px;line-height:1.5}th,td{border:1px solid #dce7e4;padding:7px 8px;text-align:left;vertical-align:top}th{background:#edf5f2;color:#315f58}.footer{margin-top:24px;padding-top:10px;border-top:1px solid #dce7e4;color:#73847f;font-size:10px}@page{size:A4;margin:12mm}@media print{body{background:#fff}.toolbar{display:none}main{width:auto;min-height:auto;margin:0;padding:0;box-shadow:none}section{break-inside:auto}thead{display:table-header-group}tr{break-inside:avoid}}`

export function buildVetReportHtml({ pet, reminders, growthRecords, generatedAt = new Date(), locale = getLocale() }: VetReportInput) {
  const t = (key: TranslationKeys) => translate(key, locale)
  const text = (value?: string) => value?.trim() ? escapeHtml(value.trim()).replace(/\n/g, '<br>') : t('vetReportMissing')
  const petReminders = reminders.filter((item) => item.petId === pet.id)
  const medications = petReminders.filter((item) => item.kind === 'medication' && item.enabled)
  const visits = petReminders.filter((item) => item.kind === 'vet' && item.vetVisit?.updatedAt).sort((a, b) => b.startDate.localeCompare(a.startDate))
  const growth = growthRecords.filter((item) => item.petId === pet.id).sort((a, b) => b.date.localeCompare(a.date)).slice(0, 12)
  const timeline = buildHealthTimeline(petReminders, pet.id, generatedAt).slice(0, 100)
  const title = interpolate(t('vetReportTitle'), { pet: pet.name })
  const table = <T,>(items: T[], render: (item: T) => string, columns: number) => items.length ? items.map(render).join('') : `<tr><td colspan="${columns}">${t('vetReportNoRecords')}</td></tr>`
  const schedule = (item: CareReminder) => interpolate(t('vetReportRepeatSchedule'), { repeat: t(repeatKeys[item.repeat]), times: (item.dailyTimes.length ? item.dailyTimes : [item.time]).join(', ') })
  const fact = (label: string, value: string) => `<div class="fact"><b>${label}</b><span>${value}</span></div>`
  const measurements = (record: GrowthRecord) => [record.bodyLengthCm && interpolate(t('vetReportBodyLength'), { value: record.bodyLengthCm }), record.chestCm && interpolate(t('vetReportChest'), { value: record.chestCm }), record.neckCm && interpolate(t('vetReportNeck'), { value: record.neckCm })].filter(Boolean).join(' · ')
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><style>${reportStyles}</style></head><body>
  <div class="toolbar"><p>${t('vetReportToolbar')}</p><button type="button" onclick="window.print()">${t('vetReportPrint')}</button></div><main><header><h1>${escapeHtml(title)}</h1><p>${escapeHtml(interpolate(t('vetReportGenerated'), { date: `${formatDate(generatedAt, locale)} ${formatTime(generatedAt, locale)}` }))}</p></header><div class="notice">${t('vetReportNotice')}</div>
  <section><h2>${t('vetReportBasics')}</h2><div class="grid">${fact(t('vetReportName'), escapeHtml(pet.name))}${fact(t('vetReportSpecies'), t(pet.species === 'cat' ? 'vetReportCat' : pet.species === 'dog' ? 'vetReportDog' : 'vetReportMissing'))}${fact(t('vetReportBirthday'), pet.birthDate ? escapeHtml(formatDate(pet.birthDate, locale)) : t('vetReportMissing'))}${fact(t('vetReportLatestWeight'), growth[0] ? `${escapeHtml(formatWeight(Number(growth[0].weightKg), locale))} (${escapeHtml(formatDate(growth[0].date, locale))})` : t('vetReportNoWeight'))}</div></section>
  <section><h2>${t('vetReportMedication')}</h2><table><thead><tr><th>${t('vetReportItem')}</th><th>${t('vetReportDose')}</th><th>${t('vetReportTime')}</th></tr></thead><tbody>${table(medications, item => `<tr><td>${escapeHtml(item.title)}</td><td>${text(item.dose || item.details)}</td><td>${escapeHtml(schedule(item))}</td></tr>`, 3)}</tbody></table></section>
  <section><h2>${t('vetReportVisits')}</h2><table><thead><tr><th>${t('vetReportDateItem')}</th><th>${t('vetReportDiagnosis')}</th><th>${t('vetReportInstructions')}</th></tr></thead><tbody>${table(visits.slice(0, 10), item => `<tr><td>${escapeHtml(formatDate(item.startDate, locale))}<br>${escapeHtml(item.title)}</td><td>${text(item.vetVisit?.diagnosis)}</td><td>${text([item.vetVisit?.instructions, item.vetVisit?.prescription, item.vetVisit?.nextVisitDate && interpolate(t('vetReportNextVisit'), { date: formatDate(item.vetVisit.nextVisitDate, locale) })].filter(Boolean).join('\n'))}</td></tr>`, 3)}</tbody></table></section>
  <section><h2>${t('vetReportGrowth')}</h2><table><thead><tr><th>${t('vetReportDate')}</th><th>${t('vetReportWeight')}</th><th>${t('vetReportMeasurements')}</th><th>${t('vetReportNotes')}</th></tr></thead><tbody>${table(growth, item => `<tr><td>${escapeHtml(formatDate(item.date, locale))}</td><td>${escapeHtml(formatWeight(Number(item.weightKg), locale))}</td><td>${text(measurements(item))}</td><td>${text(item.note)}</td></tr>`, 4)}</tbody></table></section>
  <section><h2>${t('vetReportTimeline')}</h2><table><thead><tr><th>${t('vetReportDateTime')}</th><th>${t('vetReportType')}</th><th>${t('vetReportItem')}</th><th>${t('vetReportContent')}</th><th>${t('vetReportStatus')}</th></tr></thead><tbody>${table(timeline, item => `<tr><td>${escapeHtml(`${formatDate(item.date, locale)} ${formatTime(item.date, locale)}`)}</td><td>${escapeHtml(t(kindKeys[item.kind]))}</td><td>${escapeHtml(item.title)}</td><td>${text(item.details)}</td><td>${escapeHtml(t(statusKeys[item.status]))}</td></tr>`, 5)}</tbody></table></section>
  <p class="footer">${t('vetReportFooter')}</p></main></body></html>`
}

export function openVetReport(input: VetReportInput) { const reportWindow = window.open('', '_blank'); if (!reportWindow) return false; reportWindow.opener = null; reportWindow.document.open(); reportWindow.document.write(buildVetReportHtml(input)); reportWindow.document.close(); window.setTimeout(() => { reportWindow.focus(); reportWindow.print() }, 450); return true }
